sudo: false
language: node_js
node_js: stable
after_success:
  - $(npm bin)/set-up-ssh --key "$encrypted_d6f906c6046a_key" --iv "$encrypted_d6f906c6046a_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - $(npm bin)/update-branch --commands "npm run build" --commit-message "Deploy website [skip ci]" --directory "build"  --distribution-branch "gh-pages" --source-branch "master"
